on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test -cover ./...
      
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      - name: Run gosec
        run: gosec ./...
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run format
        run: test -z $(go fmt ./...)
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: test -z $(staticcheck ./...)

  deploy:
    needs: [tests, style]
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Build
        run: scripts/buildprod.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info
          
      - name: Build and push docker image
        run: gcloud builds submit --tag europe-west2-docker.pkg.dev/pbifiltergen/pbifiltergen-ar-repo/pbifiltergen:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy pbifiltergen --image europe-west2-docker.pkg.dev/pbifiltergen/pbifiltergen-ar-repo/pbifiltergen:latest --region europe-west2 --allow-unauthenticated --project pbifiltergen --max-instances=1